import type { ThemePreset } from '../types';

export const themes: ThemePreset[] = [
  {
    id: 'minimal',
    name: 'Minimal / Editorial',
    colors: {
      background: '#fafafa',
      surface: '#ffffff',
      text: '#1a1a1a',
      textMuted: '#6b7280',
      accent: '#111827',
      accentHover: '#374151',
      border: '#e5e7eb',
    },
    typography: { headingFont: 'Georgia, serif', bodyFont: 'system-ui, sans-serif', headingWeight: 400 },
    spacing: { section: '6rem', card: '2rem' },
    radius: '0px',
    buttonStyle: 'solid',
    shadow: 'none',
  },
  {
    id: 'neobrutal',
    name: 'Neo-Brutal',
    colors: {
      background: '#f5f0e8',
      surface: '#fffef9',
      text: '#0d0d0d',
      textMuted: '#525252',
      accent: '#ff6b35',
      accentHover: '#e55a2b',
      border: '#0d0d0d',
    },
    typography: { headingFont: 'system-ui, sans-serif', bodyFont: 'system-ui, sans-serif', headingWeight: 800 },
    spacing: { section: '5rem', card: '1.5rem' },
    radius: '0px',
    buttonStyle: 'brutal',
    shadow: '4px 4px 0px #0d0d0d',
  },
  {
    id: 'darkneon',
    name: 'Dark / Neon',
    colors: {
      background: '#0a0a0f',
      surface: '#12121a',
      text: '#e4e4e7',
      textMuted: '#71717a',
      accent: '#a855f7',
      accentHover: '#9333ea',
      border: '#27272a',
    },
    typography: { headingFont: 'system-ui, sans-serif', bodyFont: 'system-ui, sans-serif', headingWeight: 700 },
    spacing: { section: '6rem', card: '2rem' },
    radius: '12px',
    buttonStyle: 'glow',
    shadow: '0 0 20px rgba(168, 85, 247, 0.3)',
  },
  {
    id: 'pastel',
    name: 'Pastel / Soft',
    colors: {
      background: '#fdf6f0',
      surface: '#ffffff',
      text: '#44403c',
      textMuted: '#a8a29e',
      accent: '#f9a8d4',
      accentHover: '#f472b6',
      border: '#f3e8e0',
    },
    typography: { headingFont: 'system-ui, sans-serif', bodyFont: 'system-ui, sans-serif', headingWeight: 600 },
    spacing: { section: '5rem', card: '2rem' },
    radius: '20px',
    buttonStyle: 'soft',
    shadow: '0 4px 24px rgba(0, 0, 0, 0.06)',
  },
  {
    id: 'luxury',
    name: 'Luxury / Serif',
    colors: {
      background: '#0c0c0c',
      surface: '#1a1a1a',
      text: '#f5f0e8',
      textMuted: '#a3a3a3',
      accent: '#c9a96e',
      accentHover: '#b8944d',
      border: '#2a2a2a',
    },
    typography: { headingFont: 'Georgia, serif', bodyFont: 'Georgia, serif', headingWeight: 400 },
    spacing: { section: '7rem', card: '2.5rem' },
    radius: '2px',
    buttonStyle: 'outline',
    shadow: 'none',
  },
  {
    id: 'retro',
    name: 'Retro / Pixel',
    colors: {
      background: '#2d1b69',
      surface: '#3d2b79',
      text: '#e0d4ff',
      textMuted: '#9b8ec4',
      accent: '#00ff88',
      accentHover: '#00cc6a',
      border: '#4a3890',
    },
    typography: { headingFont: 'monospace', bodyFont: 'monospace', headingWeight: 700 },
    spacing: { section: '4rem', card: '1.5rem' },
    radius: '0px',
    buttonStyle: 'pixel',
    shadow: '4px 4px 0px #00ff88',
  },
];

export function getTheme(id: string): ThemePreset {
  return themes.find(t => t.id === id) || themes[0];
}
